- name: Install Packages
  yum:
    name:
      - haproxy
      - libselinux-python
      - libsemanage-python
    state: latest

- name: Copy haproxy.cfg Template
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
    setype: etc_t

- name: Enable haproxy_connect_any
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: Enable/Start haproxy Service
  systemd:
    name: haproxy
    state: started
    enabled: yes
