---
- name: Provision OpenShift 4 Environment
  hosts: localhost
  vars_files:
    - vault.yml
  roles:
    - role: ipa
      tags:
        - ipa
    - role: rhv
      tags:
        - rhv

- name: Setup Loadbalancer Host
  hosts: loadbalancer
  become: yes
  roles:
    - role: dhcpd
      tags:
        - dhcpd
    - role: haproxy
      tags:
        - haproxy
    - role: httpd
      tags:
        - httpd
