- name: Generate IPA Session Cookie
  uri:
    url: "https://{{ ipa_hostname }}/ipa/session/login_password"
    validate_certs: no
    method: POST
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
      Accept: "text/plain"
      Referer: "https://{{ ipa_hostname }}/ipa"
    body: "user={{ ipa_username }}&password={{ ipa_password }}"
  register: ipa_session

- name: Debug ipa_session
  debug:
    var: ipa_session
    verbosity: 2

- name: Create SRV Records
  uri:
    url: "https://{{ ipa_hostname }}/ipa/session/json"
    validate_certs: no
    method: POST
    status_code: 200
    headers:
      Cookie: "{{ ipa_session.set_cookie }}"
      Accept: "application/json"
      Referer: "https://{{ ipa_hostname }}/ipa"
    body:
      method: dnsrecord_add
      params:
      - - "{{ base_domain }}."
        - _etcd-server-ssl._tcp
      - srv_part_priority: '0'
        srv_part_weight: '10'
        srv_part_port: '2380'
        srv_part_target: "{{ item }}.{{ base_domain }}."
    body_format: json
  with_items:
    - "etcd-0"
    - "etcd-1"
    - "etcd-2"

- name: Create A/PTR Records
  uri:
    url: "https://{{ ipa_hostname }}/ipa/session/json"
    validate_certs: no
    method: POST
    status_code: 200
    headers:
      Cookie: "{{ ipa_session.set_cookie }}"
      Accept: "application/json"
      Referer: "https://{{ ipa_hostname }}/ipa"
    body:
      method: dnsrecord_add
      params:
      - - "{{ base_domain }}."
        - "{{ item }}"
      - a_part_ip_address: "{{ hostvars[item].ip }}"
        a_extra_create_reverse: true
    body_format: json
  with_items:
    - "{{ groups[provision_group] }}"
