---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: storagecluster-cephfs
